version: '3.7'

services:
  postgres:
    image: kartoza/postgis:11.0-2.5
    volumes:
      - ./postgis-data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - POSTGRES_DBNAME=postgis_prod
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 backend.wsgi
    expose:
      - 8000
    environment:
      - SECRET_KEY=please_change_me
      - SQL_ENGINE=django.contrib.gis.db.backends.postgis
      - SQL_DATABASE=postgis_prod
      - SQL_USER=postgres
      - SQL_PASSWORD=postgres
      - SQL_HOST=postgres
      - SQL_PORT=5432
      - DATABASE=postgres
      - SEED_DB
    depends_on:
      - postgres
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
