version: '3.7'

services:
  postgres:
    image: kartoza/postgis:11.0-2.5
    volumes:
      - ./postgis-data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - POSTGRES_DBNAME=postgis_prod
    restart: always
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 backend.wsgi
    volumes:
      - ./backend/static:/usr/src/app/backend/static
      - ./media/static:/usr/src/app/media/static
    expose:
      - 8000
    environment:
      - SECRET_KEY
      - SQL_ENGINE=django.contrib.gis.db.backends.postgis
      - SQL_DATABASE=postgis_prod
      - SQL_USER=postgres
      - SQL_PASSWORD=postgres
      - SQL_HOST=postgres
      - SQL_PORT=5432
      - DATABASE=postgres
      - SEED_DB
    restart: always
    depends_on:
      - postgres
  nginx:
    build: ./nginx
    volumes:
      - ./backend/static:/usr/src/app/backend/static
      - ./media/static:/usr/src/app/media/static
    ports:
      - 80:80
    restart: always
    depends_on:
      - web
