# Generated by Django 2.1.4 on 2018-12-27 00:26
import json
from pathlib import Path

from django.db import migrations
from django.contrib.gis.geos import fromstr


DATA_FILENAME = 'Healthy_Corner_Stores.geojson'

def load_data(apps, schema_editor):
    Store = apps.get_model('stores', 'Store')
    Profile = apps.get_model('users', 'Profile')
    jsonfile = Path(__file__).parents[3] / DATA_FILENAME

    Profile(username='Neargreen', password='12345').save()

    with open(str(jsonfile)) as datafile:
        data = json.load(datafile)
        for store in data['features']:
            try:
                properties = store['properties']
                name = properties.get('OFFICIAL_STORE_NAME','no-name')
                address = properties.get('STORE_ADDRESS', 0)
                coordinates = store['geometry']['coordinates']
                longitude = coordinates[0]
                latitude = coordinates[1]
                location = fromstr(f'POINT({longitude} {latitude})', srid=4326)
                user = Profile.objects.get(username='Neargreen')
                Store(user=user, name=name, address=address, location=location).save()
            except KeyError:
                pass  

class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_user'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]

